# Generated by Django 3.1.7 on 2021-03-07 09:10
from django.conf import settings
from django.db import migrations


def set_superuser_profile(apps, scheme_editor):
    profile_obj = apps.get_model('userprofile', 'Profile')  # from .models import profile
    user_obj = apps.get_model('main', 'User')
    user = user_obj.objects.get(email=settings.SUPERUSER_EMAIL)
    profile_obj.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('main', '0002_set_superuser'),
    ]

    operations = [
        migrations.RunPython(set_superuser_profile)
    ]
