# Generated by Django 3.1.7 on 2021-03-20 09:11

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_set_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='загрузка_1.jpg', upload_to='', validators=[product.models.validate_image], verbose_name='Изображение'),
        ),
    ]
