# Generated by Django 3.1.7 on 2021-03-07 09:42

from django.db import migrations
from django.conf import settings


def set_superuser_cart(apps, scheme_editor):
    cart_obj = apps.get_model('cart', 'UserCart')
    user_obj = apps.get_model('main', 'User')
    user = user_obj.objects.get(email=settings.SUPERUSER_EMAIL)
    cart_obj.objects.create(owner=user)


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210307_0905'),
        ('main', '0002_set_superuser'),
    ]

    operations = [
        migrations.RunPython(set_superuser_cart)
    ]
