# Generated by Django 3.1.7 on 2021-04-10 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_auto_20210320_0911'),
        ('cart', '0003_superuser_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercart',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercart_set', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user_cart', 'product')},
        ),
    ]
